print("JJJJJ   $$$   ****    &&& ")
print("  J    $   $  |   |  &   &")
print("  J    $      |   |  &    ")
print("  J    $      ****   &    ")
print("J J    $      ||     & &&&")
print("J J    $   $  | |    &   &")
print("JJJ     $$$   |  |    &&& ")
